OnboardingMVVM
bemadeveloper/Baby-s-diary pull request #2
Opened 2024-09-19 07:38 UTC by bemadeveloper

2024-09-19 07:53 UTC, pernebayevz commented on Baby's diary/OnboardingPage/View/OnboardingPageViewController.swift
> +        view.addSubview(onboardingPageView)
Лучше полностью изменить `view` с помощью метода `loadView`, а не добавлять подвиды в существующий. Это позволит сразу установить кастомное представление и уберет необходимость вызова `addSubview` в `setupUI()`. Так код будет более чистым и логичным.

2024-09-19 07:53 UTC, pernebayevz commented on Baby's diary/OnboardingPage/View/OnboardingPageViewController.swift
> +    private func bindViewModel() {
Название метода `bindViewModel()` не совсем соответствует тому, что делает код, так как здесь нет байндинга в традиционном смысле (с использованием реактивного обновления данных). Лучше переименовать метод, например, в `configureView()` или что-то более описательное, отражающее суть процесса конфигурации UI.

2024-09-19 07:53 UTC, pernebayevz commented on Baby's diary/Resources/Assets.xcassets/baby.imageset/Contents.json
где используется этот код в данном PR? Если нигде, то убрать.

2024-09-19 07:53 UTC, pernebayevz commented on Baby's diary/Resources/Assets.xcassets/baby.imageset/appicon 2.png
где используется это изображение в данном PR? Если нигде, то убрать.

2024-09-20 13:15 UTC, bemadeveloper commented on Baby's diary/Resources/Assets.xcassets/baby.imageset/appicon 2.png
исправила, можете подтвердить и смержить?

2024-09-20 16:43 UTC, pernebayevz requested changes

2024-09-20 16:43 UTC, pernebayevz commented on Baby's diary/OnboardingPage/View/OnboardingPageView.swift
> +    func configure(with viewModel: OnboardingPageViewModel) {
viewModel shouldn't appear here

2024-09-22 13:08 UTC, merged